In [37]:
import os
import glob
import pandas as pd
import numpy as np

ptdfs_path = r"C:\Users\UI450907\Desktop\TE RWEST\Tesis\Phase3Results\PTDFs"
limits_path = r"C:\Users\UI450907\Desktop\TE RWEST\Tesis\Phase3Results\Limits"



ptdf_dfs = {}
limits_dfs = {}

In [38]:
def load_csv_folder(folder_path, sep=";", decimal="."):
    """
    Load all CSV files from a folder into a dictionary of DataFrames.

    Parameters
    ----------
    folder_path : str
        Path to the folder containing CSV files.
    sep : str, optional
        CSV separator, by default ";"
    decimal : str, optional
        Decimal separator, by default "."

    Returns
    -------
    dict
        Dictionary where:
        - key = file name without extension
        - value = pandas DataFrame
    """
    csv_files = glob.glob(os.path.join(folder_path, "*.csv"))
    dfs = {}

    for file in csv_files:
        name = os.path.splitext(os.path.basename(file))[0]
        df = pd.read_csv(file, sep=sep, decimal=decimal)
        dfs[name] = df

    return dfs

def filter_ptdf_columns(df):
    """
    This function receives a ptdf result dataframe from powerfactory and clean the columns
    It returns a cleaned dataframe with only the ptdf for lines and trafos of the 
    original dataframe 
    """
    df.rename(columns={df.columns[0]:"Injection Bus"}, inplace=True)

    first_col = df.columns[0] # Keep the bus index
    cols = [first_col]
    seen_elements = set()
    df = df.iloc[1:].reset_index(drop = True)
    for c in df.columns[1:]:
        # keep only lines and trafos
        if not (c.startswith("Line") or c.startswith("Trf")):
            continue

        # remove .1, .2 etc
        if any(f".{i}" in c for i in range(1, 10)):
            continue

        # avoid duplicates (just in case)
        if c not in seen_elements:
            cols.append(c)
            seen_elements.add(c)

    return df[cols]

def reshape_ptdf(df):
    """
    Transform PTDF dataframe from wide to long format.

    Parameters
    ----------
    df : pandas.DataFrame
        PTDF dataframe (wide format)

    Returns
    -------
    pandas.DataFrame
        Long format with columns:
        - Injection Bus
        - Element
        - PTDF
    """
    df_long = df.melt(
        id_vars="Injection Bus",
        var_name="Element",
        value_name="PTDF"
    )

    df_long["PTDF"] = pd.to_numeric(df_long["PTDF"],errors = "coerce")
    df_long["PTDF"] = df_long["PTDF"].fillna(0)

    return df_long

def combine_limits(limits_dfs):
    """
    Combine line and transformer limits into a single dataframe.

    Parameters
    ----------
    limits_dfs : dict
        Dictionary containing limits dataframes
        Expected keys: 'limits_lines', 'limits_trafos'

    Returns
    -------
    pandas.DataFrame
        Combined limits dataframe with unified 'Element' column
    """
    # Copy to avoid modifying original data
    limit_lines = limits_dfs["limits_lines"].copy()
    limit_trafos = limits_dfs["limits_trafos"].copy()

    # Standardize column name
    limit_lines = limit_lines.rename(columns={"name": "Element"})
    limit_trafos = limit_trafos.rename(columns={"name": "Element"})

    # Combine
    limit_elements = pd.concat([limit_lines, limit_trafos], ignore_index=True)

    return limit_elements

def merge_ptdf_with_limits(df_long, limits_df):
    """
    Merge one PTDF long dataframe with the combined limits dataframe.

    Parameters
    ----------
    df_long : pandas.DataFrame
        Long PTDF dataframe with columns like:
        - Injection Bus
        - Element
        - PTDF
    limits_df : pandas.DataFrame
        Combined limits dataframe with column:
        - Element

    Returns
    -------
    pandas.DataFrame
        Merged and sorted dataframe
    """
    result = df_long.merge(limits_df, on="Element", how="left")

    result["Injection Bus"] = pd.to_numeric(
        result["Injection Bus"], errors="coerce"
    )
    result["Injection Bus"] = result["Injection Bus"].astype("Int64")

    result = result.sort_values(by=["Injection Bus", "Element"])
    result = result.reset_index(drop=True)

    return result

def merge_ptdf_with_limits_dict(ptdf_dict,loading_dict):
    results = {}
    for case in ptdf_dict.keys():
        df_ptdf = ptdf_dict[case]
        df_loading = loading_dict[case]

        df = df_ptdf.merge(df_loading,on = "Element", how = "left")
        df["Injection Bus"] = pd.to_numeric(df["Injection Bus"], errors="coerce").astype("Int64")

        df = df.sort_values(by=["Injection Bus", "Element"]).reset_index(drop=True)

        results[case] = df

    return results






def calculate_transfer_limit(df):
    """
    Calculate transfer limit based on PTDF and element limits.

    Parameters
    ----------
    df : pandas.DataFrame
        DataFrame containing:
        - PTDF
        - smax
        - p_used

    Returns
    -------
    pandas.DataFrame
        DataFrame with added 'Transfer Limit' column
    """
    # Calculate transfer limit
    margin = df["smax"] - df["p_used"]
    df["Transfer Limit"] = np.where(
        df["PTDF"] == 0,
        np.inf,  # element not limiting
        (margin/ df["PTDF"]).abs())

    return df

In [39]:
ptdf_dfs = load_csv_folder(ptdfs_path)
limits_dfs = load_csv_folder(limits_path)

ptdf_dfs_filtered = {}
for name,df in ptdf_dfs.items():
    filtered_df = filter_ptdf_columns(df)
    filtered_df = filtered_df.reset_index(drop = True)
    ptdf_dfs_filtered[name] = filtered_df

ptdf_long_dfs = {}
for name, df in ptdf_dfs_filtered.items():
    df = reshape_ptdf(df)
    ptdf_long_dfs[name] = df


limits_combined = combine_limits(limits_dfs)

results = {}
for name,df_long in ptdf_long_dfs.items():
    result = merge_ptdf_with_limits(df_long,limits_combined)
    results[name] = result

for name,result in results.items():
    df = calculate_transfer_limit(result)
    results[name] = df

for name,result in results.items():
    groups = result.groupby("Injection Bus")
    print(f"\n CASE: {name}")
    for bus,df_bus in groups:
        top5 = df_bus.sort_values("Transfer Limit").head(10)
        print(f"\nBus {bus}")
        print(top5[["Element", "PTDF", "Transfer Limit"]])

 CASE: Distribution_Factors_Results_(SYM)_Base

Bus 1
         Element      PTDF  Transfer Limit
35   Trf 06 - 31  1.005349      142.177731
8   Line 05 - 06  0.537879      264.227273
2   Line 02 - 03  0.446103      520.982676
10  Line 06 - 07 -0.257771      651.812421
0   Line 01 - 02  0.549658      858.324198
1   Line 01 - 39  0.450342      976.890920
13  Line 08 - 09 -0.448873     1090.120640
11  Line 06 - 11 -0.208733     1126.074831
4   Line 03 - 04  0.376103     1168.763316
14  Line 09 - 39 -0.449094     1173.092938

Bus 2
         Element      PTDF  Transfer Limit
81   Trf 06 - 31  0.998067      143.215074
54  Line 05 - 06  0.558934      254.273853
48  Line 02 - 03  0.633141      367.077688
50  Line 03 - 04  0.534940      821.728398
57  Line 06 - 11 -0.284849      825.170450
61  Line 10 - 11  0.261502      881.262759
52  Line 04 - 05  0.497678      925.988540
65  Line 15 - 16 -0.248558     1019.358163
56  Line 06 - 07 -0.153282     1096.138748
63  Line 13 - 14 -0.286378     1133.277926

Bus 3
          Element      PTDF  Transfer Limit
127   Trf 06 - 31  1.003232      142.477751
100  Line 05 - 06  0.576505      246.523970
96   Line 03 - 04  0.619295      709.799674
103  Line 06 - 11 -0.301973      778.377463
98   Line 04 - 05  0.555742      829.241131
107  Line 10 - 11  0.277236      831.248373
111  Line 15 - 16 -0.239523     1057.809171
109  Line 13 - 14 -0.303582     1069.055036
108  Line 10 - 13 -0.277236     1132.570201
94   Line 02 - 03 -0.171439     1355.653817

Bus 4
          Element      PTDF  Transfer Limit
173   Trf 06 - 31  1.004717      142.267165
146  Line 05 - 06  0.638912      222.444251
144  Line 04 - 05  0.673412      684.342014
149  Line 06 - 11 -0.274184      857.267301
153  Line 10 - 11  0.251716      915.523741
155  Line 13 - 14 -0.275617     1177.524847
154  Line 10 - 13 -0.251716     1247.394811
145  Line 04 - 14  0.247416     1310.204741
148  Line 06 - 07 -0.090464     1857.295051
140  Line 02 - 03 -0.052742     4406.581752

Bus 5
          Element      PTDF  Transfer Limit
219   Trf 06 - 31  1.002382      142.598570
192  Line 05 - 06  0.864970      164.308937
194  Line 06 - 07 -0.089980     1867.285392
193  Line 05 - 08  0.088620     3089.823930
196  Line 07 - 08 -0.089507     4592.428369
195  Line 06 - 11 -0.045873     5123.906821
199  Line 10 - 11  0.041969     5491.004648
201  Line 13 - 14 -0.046038     7049.521392
200  Line 10 - 13 -0.041969     7481.456127
191  Line 04 - 14  0.038889     8335.663458

Bus 6
          Element      PTDF  Transfer Limit
265   Trf 06 - 31  1.000502      142.866520
256  Line 21 - 22 -0.000028   195390.907551
241  Line 06 - 11 -0.001089   215839.281543
245  Line 10 - 11  0.000846   272401.860602
247  Line 13 - 14 -0.001015   319749.621527
246  Line 10 - 13 -0.000846   371145.664518
249  Line 15 - 16 -0.000613   413327.285780
240  Line 06 - 07  0.000356   471961.627908
238  Line 05 - 06 -0.000235   604775.751079
250  Line 16 - 17 -0.000475   780280.841711

Bus 7
          Element      PTDF  Transfer Limit
311   Trf 06 - 31  1.006060      142.077251
286  Line 06 - 07 -0.657137      255.682361
284  Line 05 - 06  0.321673      441.822290
285  Line 05 - 08 -0.321644      851.314486
288  Line 07 - 08  0.346208     1187.304990
287  Line 06 - 11 -0.026662     8815.879439
291  Line 10 - 11  0.024264     9497.690985
278  Line 02 - 03  0.020145    11536.953823
293  Line 13 - 14 -0.026691    12159.374540
292  Line 10 - 13 -0.024264    12940.538748

Bus 8
          Element      PTDF  Transfer Limit
357   Trf 06 - 31  1.007744      141.839832
330  Line 05 - 06  0.484193      293.524073
332  Line 06 - 07 -0.483278      347.663952
331  Line 05 - 08 -0.484027      565.712650
334  Line 07 - 08 -0.480799      854.940393
333  Line 06 - 11 -0.039391     5967.073128
337  Line 10 - 11  0.035946     6411.060315
324  Line 02 - 03  0.030241     7685.325709
339  Line 13 - 14 -0.039484     8219.680525
338  Line 10 - 13 -0.035946     8735.025655

Bus 9
          Element      PTDF  Transfer Limit
403   Trf 06 - 31  1.007319      141.899676
376  Line 05 - 06  0.507754      279.903854
378  Line 06 - 07 -0.386173      435.085673
381  Line 08 - 09 -0.740748      660.583251
377  Line 05 - 08 -0.358946      762.845098
380  Line 07 - 08 -0.384212     1069.863737
370  Line 02 - 03  0.209986     1106.797285
369  Line 01 - 39 -0.259459     1695.585856
368  Line 01 - 02  0.259459     1818.340323
382  Line 09 - 39  0.258800     2035.660742

Bus 10
          Element      PTDF  Transfer Limit
449   Trf 06 - 31  0.992273      144.051324
425  Line 06 - 11 -0.754732      311.433698
429  Line 10 - 11  0.737424      312.509457
422  Line 05 - 06  0.205120      692.873935
430  Line 10 - 13  0.262576     1195.803242
431  Line 13 - 14  0.238882     1358.603268
421  Line 04 - 14 -0.196303     1651.353348
420  Line 04 - 05  0.212330     2170.414564
424  Line 06 - 07 -0.032053     5241.891228
433  Line 15 - 16  0.040596     6241.246088

Bus 11
          Element      PTDF  Transfer Limit
495   Trf 06 - 31  0.995216      143.625343
471  Line 06 - 11 -0.834124      281.791409
468  Line 05 - 06  0.139188     1021.081570
475  Line 10 - 11 -0.147934     1557.802629
477  Line 13 - 14  0.161861     2005.089959
476  Line 10 - 13  0.147934     2122.495384
467  Line 04 - 14 -0.133172     2434.187489
466  Line 04 - 05  0.144108     3197.907989
470  Line 06 - 07 -0.021654     7759.228758
479  Line 15 - 16  0.027357     9261.601279

Bus 12
          Element      PTDF  Transfer Limit
541   Trf 06 - 31  0.995010      143.655078
517  Line 06 - 11 -0.756814      310.576942
543   Trf 11 - 12 -0.522839      492.411125
544   Trf 13 - 12 -0.477279      530.936281
514  Line 05 - 06  0.205727      690.829602
521  Line 10 - 11  0.238375      966.762345
522  Line 10 - 13 -0.238375     1317.207057
523  Line 13 - 14  0.239432     1355.482416
513  Line 04 - 14 -0.196889     1646.438431
512  Line 04 - 05  0.212994     2163.648387

Bus 13
          Element      PTDF  Transfer Limit
587   Trf 06 - 31  0.994539      143.723111
563  Line 06 - 11 -0.679437      345.946685
567  Line 10 - 11  0.624008      369.309326
568  Line 10 - 13 -0.624008      503.181421
560  Line 05 - 06  0.272087      522.341389
569  Line 13 - 14  0.316823     1024.375963
559  Line 04 - 14 -0.260432     1244.722677
558  Line 04 - 05  0.281688     1636.009075
562  Line 06 - 07 -0.042526     3950.955640
590   Trf 13 - 12  0.060546     4185.325821

Bus 14
          Element      PTDF  Transfer Limit
633   Trf 06 - 31  0.999529      143.005595
606  Line 05 - 06  0.445477      319.033983
609  Line 06 - 11 -0.483579      486.061176
613  Line 10 - 11  0.444091      518.929620
615  Line 13 - 14 -0.486208      667.504167
614  Line 10 - 13 -0.444091      707.038044
605  Line 04 - 14 -0.426513      760.036895
604  Line 04 - 05  0.461288      999.037747
608  Line 06 - 07 -0.069670     2411.631111
617  Line 15 - 16  0.087836     2884.576098

Bus 15
          Element      PTDF  Transfer Limit
679   Trf 06 - 31  0.998566      143.143507
652  Line 05 - 06  0.493821      287.801251
655  Line 06 - 11 -0.410786      572.193253
659  Line 10 - 11  0.377207      610.942994
663  Line 15 - 16  0.349746      724.438953
661  Line 13 - 14 -0.413014      785.798704
660  Line 10 - 13 -0.377207      832.405635
662  Line 14 - 15 -0.650391      863.242936
650  Line 04 - 05  0.491829      937.000715
664  Line 16 - 17  0.352002     1052.929812

Bus 16
          Element      PTDF  Transfer Limit
725   Trf 06 - 31  0.992419      144.030132
698  Line 05 - 06  0.511418      277.898513
709  Line 15 - 16 -0.535108      473.492503
701  Line 06 - 11 -0.377582      622.511077
705  Line 10 - 11  0.346684      664.732073
710  Line 16 - 17  0.462218      801.858430
707  Line 13 - 14 -0.379636      854.886960
706  Line 10 - 13 -0.346684      905.692885
696  Line 04 - 05  0.501783      918.413187
708  Line 14 - 15 -0.535237     1048.966040

Bus 17
          Element      PTDF  Transfer Limit
771   Trf 06 - 31  0.995037      143.651180
744  Line 05 - 06  0.532277      267.008158
755  Line 15 - 16 -0.432866      585.330394
747  Line 06 - 11 -0.349727      672.092740
751  Line 10 - 11  0.321101      717.693106
756  Line 16 - 17 -0.434956      852.116995
742  Line 04 - 05  0.515649      893.716704
760  Line 17 - 18  0.437963      896.317239
753  Line 13 - 14 -0.351618      923.006973
752  Line 10 - 13 -0.321101      977.851929

Bus 18
          Element      PTDF  Transfer Limit
817   Trf 06 - 31  0.999503      143.009315
790  Line 05 - 06  0.549884      258.458696
801  Line 15 - 16 -0.359710      704.371928
793  Line 06 - 11 -0.331969      708.044961
797  Line 10 - 11  0.304790      756.100837
788  Line 04 - 05  0.531679      866.771350
786  Line 03 - 04  0.505160      870.170618
806  Line 17 - 18 -0.429092      914.847601
787  Line 03 - 18 -0.571482      954.146693
799  Line 13 - 14 -0.333753      972.413329

Bus 19
          Element      PTDF  Transfer Limit
849  Line 16 - 19 -0.985077      109.777468
863   Trf 06 - 31  0.977171      146.277611
836  Line 05 - 06  0.503317      282.371351
847  Line 15 - 16 -0.526719      481.033770
839  Line 06 - 11 -0.371985      631.877569
843  Line 10 - 11  0.341517      674.789173
848  Line 16 - 17  0.455508      813.670451
845  Line 13 - 14 -0.374026      867.709373
844  Line 10 - 13 -0.341517      919.395615
834  Line 04 - 05  0.493623      933.595324

Bus 20
          Element      PTDF  Transfer Limit
895  Line 16 - 19 -0.986900      109.574687
909   Trf 06 - 31  0.978984      146.006717
882  Line 05 - 06  0.504253      281.847211
893  Line 15 - 16 -0.527698      480.141343
885  Line 06 - 11 -0.372673      630.711046
889  Line 10 - 11  0.342149      673.542737
894  Line 16 - 17  0.456348      812.172727
891  Line 13 - 14 -0.374717      866.109266
913   Trf 19 - 20 -1.001802      874.173579
890  Line 10 - 13 -0.342149      917.697355

Bus 21
          Element      PTDF  Transfer Limit
946  Line 21 - 22  0.173648       31.505951
955   Trf 06 - 31  0.986999      144.821058
928  Line 05 - 06  0.508500      279.493218
942  Line 16 - 21 -0.822253      336.029120
939  Line 15 - 16 -0.532100      476.169190
931  Line 06 - 11 -0.375625      625.754350
935  Line 10 - 11  0.344872      668.224657
940  Line 16 - 17  0.459894      805.910492
937  Line 13 - 14 -0.377676      859.323510
936  Line 10 - 13 -0.344872      910.451507

Bus 22
           Element      PTDF  Transfer Limit
992   Line 21 - 22 -0.639847        8.550396
1001   Trf 06 - 31  0.977545      146.221647
974   Line 05 - 06  0.503485      282.277131
988   Line 16 - 21 -0.636636      434.001458
985   Line 15 - 16 -0.526904      480.864875
977   Line 06 - 11 -0.372147      631.602505
981   Line 10 - 11  0.341663      674.500821
994   Line 23 - 24  0.354097      731.112436
986   Line 16 - 17  0.455720      813.291933
983   Line 13 - 14 -0.374190      867.329073

Bus 23
           Element      PTDF  Transfer Limit
1038  Line 21 - 22 -0.519142       10.538437
1047   Trf 06 - 31  0.977891      146.169910
1020  Line 05 - 06  0.503669      282.174010
1031  Line 15 - 16 -0.527095      480.690627
1034  Line 16 - 21 -0.516534      534.913389
1040  Line 23 - 24  0.476304      543.528336
1023  Line 06 - 11 -0.372275      631.385340
1027  Line 10 - 11  0.341781      674.267950
1032  Line 16 - 17  0.455874      813.017193
1029  Line 13 - 14 -0.374319      867.030169

Bus 24
           Element      PTDF  Transfer Limit
1084  Line 21 - 22 -0.075269       72.685241
1093   Trf 06 - 31  0.992246      144.055244
1066  Line 05 - 06  0.511317      277.953406
1077  Line 15 - 16 -0.535007      473.581890
1081  Line 16 - 24 -0.925005      533.772083
1069  Line 06 - 11 -0.377527      622.601768
1073  Line 10 - 11  0.346632      664.831793
1078  Line 16 - 17  0.462157      801.964267
1075  Line 13 - 14 -0.379581      855.010830
1074  Line 10 - 13 -0.346632      905.828753

Bus 25
           Element      PTDF  Transfer Limit
1139   Trf 06 - 31  0.968585      147.574286
1112  Line 05 - 06  0.538879      263.736946
1106  Line 02 - 03  0.526902      441.091388
1107  Line 02 - 25 -0.723482      485.223276
1115  Line 06 - 11 -0.285555      823.130317
1108  Line 03 - 04  0.505136      870.211961
1119  Line 10 - 11  0.262157      879.060922
1110  Line 04 - 05  0.485360      949.489295
1123  Line 15 - 16 -0.266725      949.928301
1121  Line 13 - 14 -0.287104     1130.412206

Bus 26
           Element      PTDF  Transfer Limit
1185   Trf 06 - 31  0.980575      145.769818
1158  Line 05 - 06  0.534942      265.677964
1180  Line 26 - 27  0.561281      591.883667
1169  Line 15 - 16 -0.348826      726.349602
1161  Line 06 - 11 -0.317072      741.311051
1165  Line 10 - 11  0.291104      791.648257
1153  Line 02 - 25 -0.426301      823.479904
1152  Line 02 - 03  0.263847      880.858735
1156  Line 04 - 05  0.499742      922.164086
1154  Line 03 - 04  0.469099      937.063156

Bus 27
           Element      PTDF  Transfer Limit
1231   Trf 06 - 31  0.991130      144.217448
1204  Line 05 - 06  0.535931      265.187686
1215  Line 15 - 16 -0.388566      652.063295
1207  Line 06 - 11 -0.333220      705.386764
1211  Line 10 - 11  0.305940      753.258724
1221  Line 17 - 27 -0.703487      784.024026
1202  Line 04 - 05  0.509119      905.179584
1216  Line 16 - 17 -0.390441      949.268647
1200  Line 03 - 04  0.454974      966.154966
1213  Line 13 - 14 -0.335021      968.732903

Bus 28
           Element      PTDF  Transfer Limit
1277   Trf 06 - 31  0.969355      147.457061
1250  Line 05 - 06  0.528666      268.831931
1272  Line 26 - 27  0.555302      598.256546
1275  Line 28 - 29  0.376135      699.061646
1273  Line 26 - 28 -0.616998      733.563544
1261  Line 15 - 16 -0.345154      734.077039
1253  Line 06 - 11 -0.313620      749.470626
1257  Line 10 - 11  0.287929      800.377781
1245  Line 02 - 25 -0.421031      833.787314
1244  Line 02 - 03  0.260367      892.632072

Bus 29
           Element      PTDF  Transfer Limit
1323   Trf 06 - 31  0.960481      148.819435
1296  Line 05 - 06  0.523761      271.349531
1321  Line 28 - 29 -0.496636      529.445212
1318  Line 26 - 27  0.550404      603.580382
1307  Line 15 - 16 -0.342129      740.567523
1299  Line 06 - 11 -0.310823      756.214880
1303  Line 10 - 11  0.285359      807.586143
1320  Line 26 - 29 -0.488974      825.632037
1291  Line 02 - 25 -0.417012      841.823033
1290  Line 02 - 03  0.257791      901.551779

Bus 30
           Element      PTDF  Transfer Limit
1369   Trf 06 - 31  0.998155      143.202448
1342  Line 05 - 06  0.558975      254.255202
1336  Line 02 - 03  0.633628      366.795556
1368   Trf 02 - 30 -1.000000      723.542025
1338  Line 03 - 04  0.534992      821.648528
1345  Line 06 - 11 -0.284845      825.182038
1349  Line 10 - 11  0.261498      881.276239
1340  Line 04 - 05  0.497644      926.051805
1353  Line 15 - 16 -0.248460     1019.760228
1344  Line 06 - 07 -0.153334     1095.767015

Bus 31
           Element  PTDF  Transfer Limit
1380  Line 01 - 02   0.0             inf
1381  Line 01 - 39   0.0             inf
1382  Line 02 - 03   0.0             inf
1383  Line 02 - 25   0.0             inf
1384  Line 03 - 04   0.0             inf
1385  Line 03 - 18   0.0             inf
1386  Line 04 - 05   0.0             inf
1387  Line 04 - 14   0.0             inf
1388  Line 05 - 06   0.0             inf
1389  Line 05 - 08   0.0             inf

Bus 32
           Element      PTDF  Transfer Limit
1462   Trf 10 - 32 -1.000000      106.678722
1461   Trf 06 - 31  0.991904      144.104913
1437  Line 06 - 11 -0.754454      311.548454
1441  Line 10 - 11  0.737136      312.631555
1434  Line 05 - 06  0.204902      693.611099
1442  Line 10 - 13  0.262864     1194.493092
1443  Line 13 - 14  0.239172     1356.955939
1433  Line 04 - 14 -0.196075     1653.273575
1432  Line 04 - 05  0.211981     2173.987878
1436  Line 06 - 07 -0.032186     5220.230521

Bus 33
           Element      PTDF  Transfer Limit
1493  Line 16 - 19 -0.976033      110.794675
1507   Trf 06 - 31  0.968092      147.649438
1512   Trf 19 - 33 -0.990877      158.156418
1480  Line 05 - 06  0.498568      285.061018
1491  Line 15 - 16 -0.521776      485.590802
1483  Line 06 - 11 -0.368589      637.699382
1487  Line 10 - 11  0.338391      681.022764
1492  Line 16 - 17  0.451391      821.091692
1489  Line 13 - 14 -0.370616      875.693078
1488  Line 10 - 13 -0.338391      927.888839

Bus 34
           Element      PTDF  Transfer Limit
1559   Trf 20 - 34 -0.990770       36.401925
1539  Line 16 - 19 -0.977684      110.607577
1553   Trf 06 - 31  0.969780      147.392439
1526  Line 05 - 06  0.499471      284.545652
1537  Line 15 - 16 -0.522709      484.724055
1529  Line 06 - 11 -0.369204      636.637137
1533  Line 10 - 11  0.338959      679.881561
1538  Line 16 - 17  0.452124      819.760508
1535  Line 13 - 14 -0.371232      874.240006
1557   Trf 19 - 20 -0.992511      882.356810

Bus 35
           Element      PTDF  Transfer Limit
1590  Line 21 - 22 -0.639469        8.555451
1599   Trf 06 - 31  0.977421      146.240197
1606   Trf 22 - 35 -1.000000      148.302103
1572  Line 05 - 06  0.503376      282.338255
1586  Line 16 - 21 -0.636250      434.264758
1583  Line 15 - 16 -0.526807      480.953416
1575  Line 06 - 11 -0.372139      631.616083
1579  Line 10 - 11  0.341650      674.526486
1592  Line 23 - 24  0.354465      730.353407
1584  Line 16 - 17  0.455736      813.263380

Bus 36
           Element      PTDF  Transfer Limit
1636  Line 21 - 22 -0.517623       10.569363
1645   Trf 06 - 31  0.972621      146.961910
1653   Trf 23 - 36 -0.994860      165.763909
1618  Line 05 - 06  0.500869      283.751443
1629  Line 15 - 16 -0.524195      483.349948
1632  Line 16 - 21 -0.515008      536.498370
1638  Line 23 - 24  0.472660      547.718699
1621  Line 06 - 11 -0.370340      634.684284
1625  Line 10 - 11  0.339995      677.809892
1630  Line 16 - 17  0.453554      817.175904

Bus 37
           Element      PTDF  Transfer Limit
1691   Trf 06 - 31  0.961903      148.599432
1700   Trf 25 - 37 -0.993866      175.683404
1664  Line 05 - 06  0.534936      265.680944
1658  Line 02 - 03  0.519530      447.350364
1659  Line 02 - 25 -0.714387      491.400748
1667  Line 06 - 11 -0.284030      827.549828
1660  Line 03 - 04  0.500876      877.613200
1671  Line 10 - 11  0.260755      883.787364
1675  Line 15 - 16 -0.266023      952.435038
1662  Line 04 - 05  0.481947      956.213286

Bus 38
           Element      PTDF  Transfer Limit
1737   Trf 06 - 31  0.947907      150.793527
1747   Trf 29 - 38 -0.987302      193.579108
1710  Line 05 - 06  0.516836      274.985298
1735  Line 28 - 29 -0.490048      536.562852
1732  Line 26 - 27  0.543398      611.362310
1721  Line 15 - 16 -0.337793      750.073643
1713  Line 06 - 11 -0.306834      766.046063
1717  Line 10 - 11  0.281693      818.096204
1734  Line 26 - 29 -0.482888      836.037756
1705  Line 02 - 25 -0.411378      853.352164

Bus 39
           Element      PTDF  Transfer Limit
1783   Trf 06 - 31  1.007282      141.904888
1756  Line 05 - 06  0.523503      271.483261
1758  Line 06 - 07 -0.321646      522.370368
1750  Line 02 - 03  0.329593      705.148273
1761  Line 08 - 09 -0.593943      823.859734
1762  Line 09 - 39 -0.594252      886.541400
1757  Line 05 - 08 -0.275805      992.803599
1749  Line 01 - 39 -0.406400     1082.517251
1748  Line 01 - 02  0.406400     1160.887701
1760  Line 07 - 08 -0.320021     1284.460976

 CASE: Distribution_Factors_Results_(SYM)_LODF

Bus 1
         Element       PTDF  Transfer Limit
2   Line 02 - 03  81.240493        2.860789
10  Line 06 - 07  43.955973        3.822423
1   Line 01 - 39 -99.602301        4.416916
9   Line 05 - 08  56.455230        4.850218
13  Line 08 - 09  99.773023        4.904389
14  Line 09 - 39  99.548246        5.292198
4   Line 03 - 04  68.561829        6.411372
6   Line 04 - 05  66.434563        6.936813
11  Line 06 - 11 -32.845289        7.156246
15  Line 10 - 11  30.192939        7.632645

Bus 2
         Element        PTDF  Transfer Limit
36  Line 02 - 03   80.603977        2.883380

In [40]:
ptdf_dfs_filtered["Distribution_Factors_Results_(SYM)_Base"].head()
#Seller: bus 1 : Hago inyeccion
#Buyer: Bus2: Extraigo
#PTDF_B1 ; PTDF_B2 : PTDF_1->2 = PTDF_1 - PTDF_2 = 0.5496 - (-0.2127) = 
#PTDF 1->2 : Line 01-02, Line 01-39:

,Injection Bus,Line 01 - 02,Line 01 - 39,Line 02 - 03,Line 02 - 25,Line 03 - 04,Line 03 - 18,Line 04 - 05,Line 04 - 14,Line 05 - 06,...,Trf 10 - 32,Trf 11 - 12,Trf 13 - 12,Trf 19 - 20,Trf 19 - 33,Trf 20 - 34,Trf 22 - 35,Trf 23 - 36,Trf 25 - 37,Trf 29 - 38
0,1.000000,0.549658,0.450342,0.446103,0.107961,0.376103,0.066178,0.343352,0.032026,0.537879,...,----,-0.018670,0.018674,-0.000007,-0.000007,-0.000006,----,-0.000003,----,0.000001
1,2.000000,-0.212760,0.212760,0.633141,0.152401,0.534940,0.092754,0.497678,0.036196,0.558934,...,----,-0.025446,0.025451,-0.000003,-0.000004,-0.000003,----,-0.000001,----,0.000002
2,3.000000,-0.142717,0.142717,-0.171439,0.027586,0.619295,0.210863,0.555742,0.062224,0.576505,...,----,-0.026955,0.026960,-0.000018,-0.000019,-0.000017,----,-0.000007,----,-0.000003
3,4.000000,-0.054118,0.054118,-0.052742,-0.001804,-0.079485,0.027304,0.673412,0.247416,0.638912,...,----,-0.024463,0.024467,-0.000021,-0.000022,-0.000019,----,-0.000008,----,-0.000003
4,5.000000,-0.001083,0.001083,-0.002537,0.001448,-0.007529,0.005079,-0.046312,0.038889,0.864970,...,----,-0.004167,0.004167,-0.000013,-0.000014,-0.000012,----,-0.000005,----,-0.000002

# Logic of the code

1. Read the CSV results from Powerfactory into a dictionary of dataframes : raw_dfs_ptdfs
2. Read the CSV limit results from Powerfactory : raw_dfs_limts
3. Filter the columns of the raw Dataframe of PTDFS to extract only the columns of interest : dfs_ptdfs_filtered
4. Combine the limits into one single Dataframe of limits: dfs_limits_combined
5. Reshape the dfs_ptdfs_filtered dictionary, melt function, transform from wide to long format, id: injection bus, variable: Element, value: PTDF (create function)
6. Rename the dfs_limits_combined dataframe column: "name" to "Element" so merging is possible
7. Merge on element, how: left -> as a result the dictionary of results is created 
8. Transform the relevant columns into the correct type of variable so operating is possible, do it  for each df in the dict of dfs
9. Calculate the transfer limit of each element, for each bus, for each case
10. Order the results to observe the max to the less impacted elements for each bus/case
11. Present the table results

In [41]:
import re
import pandas as pd

def normalize(key):
    key = key.replace("Distribution_Factors_Results_(SYM)_","")
    key = key.replace("Base Case", "Base")
    key = re.sub(r"_+", "_", key)
    return key


def calculate_transfer_limit(df, eps=1e-6):
    df = df.copy()

    margin = df["smax"] - df["actual"]

    df["Transfer Limit"] = np.where(
        margin.notna() & df["PTDF"].notna() & (df["PTDF"] > eps),
        margin / df["PTDF"],
        np.inf
    )

    return df

def calculate_transfer_limit_2(df):
    df = df.copy()

    margin = df["smax"] - df["actual"]

    df["Transfer Limit"] = np.where(
        df["PTDF"] == 0,
        np.inf,  # element not limiting
        (margin / df["PTDF"]).abs()
    )

    return df
def calculate_transfer_limit_3(df):
    df = df.copy()
    df["Limit Used"] = np.sign(df["PTDF"]) * df["smax"]

    margin = df["Limit Used"] - df["actual"]

    df["Transfer Limit"] = np.where(
        df["PTDF"] == 0,
        np.inf,  # element not limiting
        (margin / df["PTDF"]).abs()
    )

    return df
# PTDFS
ptdf_dfs = load_csv_folder(ptdfs_path)
ptdf_dfs_filtered = {}
for name, df in ptdf_dfs.items():
    filtered_df = filter_ptdf_columns(df)
    filtered_df = filtered_df.reset_index(drop=True)
    ptdf_dfs_filtered[name] = filtered_df

ptdf_long_dfs = {}
for name, df in ptdf_dfs_filtered.items():
    df_long = reshape_ptdf(df)
    ptdf_long_dfs[name] = df_long

# LOADINGS FROM CSV
df_loadings = pd.read_csv(r"C:\Users\UI450907\Desktop\TE RWEST\Tesis\Phase3Results\loadings_all.csv")
loading_dict = {}

for case,df_case in df_loadings.groupby("case"):
    df_case = df_case.copy()
    df_case = df_case.rename(columns={"name":"Element"})
    loading_dict[case] = df_case

# build normalized mapping

ptdf_map = {normalize(k): k for k in ptdf_long_dfs.keys()}
loading_map = {normalize(k): k for k in loading_dict.keys()}

valid_cases = set(ptdf_map.keys()) & set(loading_map.keys())

#Merge by case
results = {}

for case in valid_cases:
    ptdf_name = ptdf_map[case]
    loading_name = loading_map[case]

    df_long = ptdf_long_dfs[ptdf_name]
    df_loading = loading_dict[loading_name]

    result = merge_ptdf_with_limits(df_long, df_loading)
    results[case] = result

for name, result in results.items():
    results[name] = calculate_transfer_limit_3(result)

In [42]:
# Top 10 elements per contingncy
for name, result in results.items():
    groups = result.groupby("Injection Bus")
    print(f"\nCASE: {name}")
    for bus, df_bus in groups:
        top10 = df_bus.sort_values("Transfer Limit").head(10)
        print(f"\nBus {bus}")
        print(top10[["Element", "PTDF","Limit Used","actual","Transfer Limit"]])

CASE: Line_21_22_Cnt

Bus 1
         Element      PTDF  Limit Used      actual  Transfer Limit
2   Line 02 - 03  0.444865  597.557529  364.999062      522.761886
1   Line 01 - 39  0.452495  597.557529  122.728259     1049.358048
11  Line 06 - 11 -0.207583 -597.557529 -356.924904     1159.211614
35   Trf 06 - 31  1.005776  700.000000 -530.962257     1223.893050
15  Line 10 - 11  0.190530  597.557529  358.834144     1252.943810
14  Line 09 - 39 -0.451283 -597.557529  -18.550911     1283.023330
13  Line 08 - 09 -0.451123 -597.557529  -18.316462     1283.998083
0   Line 01 - 02  0.547505  597.557529 -122.728259     1315.578465
4   Line 03 - 04  0.376620  597.557529   85.971831     1358.360410
19  Line 15 - 16 -0.173962 -597.557529 -304.231715     1686.148775

Bus 2
         Element      PTDF  Limit Used      actual  Transfer Limit
48  Line 02 - 03  0.631628  597.557529  364.999062      368.188976
57  Line 06 - 11 -0.283308 -597.557529 -356.924904      849.367559
61  Line 10 - 11  0.260103  597.557529  358.834144      917.803271
50  Line 03 - 04  0.535809  597.557529   85.971831      954.791161
65  Line 15 - 16 -0.244893 -597.557529 -304.231715     1197.771325
81   Trf 06 - 31  0.998433  700.000000 -530.962257     1232.894202
52  Line 04 - 05  0.496592  597.557529 -147.670519     1500.684762
54  Line 05 - 06  0.559410  597.557529 -464.899174     1899.245103
76  Line 26 - 27  0.155527  597.557529  263.795054     2146.009851
46  Line 01 - 02 -0.215542 -597.557529 -122.728259     2202.954737

Bus 3
          Element      PTDF  Limit Used      actual  Transfer Limit
103  Line 06 - 11 -0.300728 -597.557529 -356.924904      800.167010
96   Line 03 - 04  0.620780  597.557529   85.971831      824.101449
107  Line 10 - 11  0.276112  597.557529  358.834144      864.588950
127   Trf 06 - 31  1.004032  700.000000 -530.962257     1226.018948
111  Line 15 - 16 -0.236203 -597.557529 -304.231715     1241.837797
98   Line 04 - 05  0.555352  597.557529 -147.670519     1341.902158
100  Line 05 - 06  0.577341  597.557529 -464.899174     1840.258535
110  Line 14 - 15 -0.236287 -597.557529   15.799051     2595.811786
109  Line 13 - 14 -0.302295 -597.557529  283.732511     2915.331182
97   Line 03 - 18  0.207604  597.557529  -44.841708     3094.349031

Bus 4
          Element      PTDF  Limit Used      actual  Transfer Limit
149  Line 06 - 11 -0.273784 -597.557529 -356.924904      878.914124
153  Line 10 - 11  0.251366  597.557529  358.834144      949.704352
144  Line 04 - 05  0.673699  597.557529 -147.670519     1106.173599
173   Trf 06 - 31  1.005419  700.000000 -530.962257     1224.327625
146  Line 05 - 06  0.639567  597.557529 -464.899174     1661.212513
155  Line 13 - 14 -0.275180 -597.557529  283.732511     3202.594810
145  Line 04 - 14  0.247203  597.557529 -266.617079     3495.809549
154  Line 10 - 13 -0.251366 -597.557529  291.165856     3535.575154
147  Line 05 - 08  0.035739  597.557529  317.045632     7848.901662
142  Line 03 - 04 -0.079401 -597.557529   85.971831     8608.573693

Bus 5
          Element      PTDF  Limit Used      actual  Transfer Limit
219   Trf 06 - 31  1.002686  700.000000 -530.962257     1227.664749
192  Line 05 - 06  0.865224  597.557529 -464.899174     1227.955654
193  Line 05 - 08  0.088666  597.557529  317.045632     3163.691793
195  Line 06 - 11 -0.045765 -597.557529 -356.924904     5258.005560
199  Line 10 - 11  0.041872  597.557529  358.834144     5701.265383
196  Line 07 - 08 -0.089592 -597.557529  187.617871     8763.900795
190  Line 04 - 05 -0.045988 -597.557529 -147.670519     9782.704399
194  Line 06 - 07 -0.090078 -597.557529  422.542845    11324.633911
201  Line 13 - 14 -0.045924 -597.557529  283.732511    19190.184646
200  Line 10 - 13 -0.041872 -597.557529  291.165856    21224.765575

Bus 6
          Element      PTDF  Limit Used      actual  Transfer Limit
265   Trf 06 - 31  1.000686  700.000000 -530.962257     1230.118395
241  Line 06 - 11 -0.001186 -597.557529 -356.924904   202894.287068
253  Line 16 - 24 -0.000124 -597.557529 -628.910624   252847.547142
245  Line 10 - 11  0.000933  597.557529  358.834144   255866.435297
249  Line 15 - 16 -0.000742 -597.557529 -304.231715   395317.807459
240  Line 06 - 07  0.000345  597.557529  422.542845   507288.938432
251  Line 16 - 19 -0.000125 -597.557529 -501.921889   765085.119893
260  Line 26 - 27  0.000434  597.557529  263.795054   769037.958829
247  Line 13 - 14 -0.001112 -597.557529  283.732511   792527.014120
238  Line 05 - 06 -0.000156 -597.557529 -464.899174   850374.064988

Bus 7
          Element      PTDF  Limit Used      actual  Transfer Limit
288  Line 07 - 08  0.346196  597.557529  187.617871     1184.125921
311   Trf 06 - 31  1.006445  700.000000 -530.962257     1223.079509
286  Line 06 - 07 -0.657219 -597.557529  422.542845     1552.146809
285  Line 05 - 08 -0.321552 -597.557529  317.045632     2844.339829
284  Line 05 - 06  0.321880  597.557529 -464.899174     3300.785085
287  Line 06 - 11 -0.026737 -597.557529 -356.924904     8999.985954
291  Line 10 - 11  0.024334  597.557529  358.834144     9810.281258
278  Line 02 - 03  0.020261  597.557529  364.999062    11478.133675
290  Line 09 - 39  0.026003  597.557529  -18.550911    23693.744557
289  Line 08 - 09  0.025806  597.557529  -18.316462    23865.534765

Bus 8
          Element      PTDF  Limit Used      actual  Transfer Limit
357   Trf 06 - 31  1.008194  700.000000 -530.962257     1220.957729
334  Line 07 - 08 -0.480893 -597.557529  187.617871     1632.744498
331  Line 05 - 08 -0.483842 -597.557529  317.045632     1890.293031
332  Line 06 - 07 -0.483425 -597.557529  422.542845     2110.152296
330  Line 05 - 06  0.484409  597.557529 -464.899174     2193.305044
333  Line 06 - 11 -0.039443 -597.557529 -356.924904     6100.768817
337  Line 10 - 11  0.035995  597.557529  358.834144     6632.126243
324  Line 02 - 03  0.030416  597.557529  364.999062     7645.925381
336  Line 09 - 39  0.038770  597.557529  -18.550911    15891.370640
335  Line 08 - 09  0.038537  597.557529  -18.316462    15981.368299

Bus 9
          Element      PTDF  Limit Used      actual  Transfer Limit
381  Line 08 - 09 -0.740697 -597.557529  -18.316462      782.021619
370  Line 02 - 03  0.210338  597.557529  364.999062     1105.641712
403   Trf 06 - 31  1.007770  700.000000 -530.962257     1221.471424
380  Line 07 - 08 -0.384343 -597.557529  187.617871     2042.902824
376  Line 05 - 06  0.508147  597.557529 -464.899174     2090.845175
379  Line 06 - 11 -0.112323 -597.557529 -356.924904     2142.327257
383  Line 10 - 11  0.102994  597.557529  358.834144     2317.837778
382  Line 09 - 39  0.258938  597.557529  -18.550911     2379.366643
377  Line 05 - 08 -0.358810 -597.557529  317.045632     2548.990164
378  Line 06 - 07 -0.386348 -597.557529  422.542845     2640.366647

Bus 10
          Element      PTDF  Limit Used      actual  Transfer Limit
425  Line 06 - 11 -0.755909 -597.557529 -356.924904      318.335440
429  Line 10 - 11  0.738546  597.557529  358.834144      323.234279
430  Line 10 - 13  0.261454  597.557529  291.165856     1171.876021
449   Trf 06 - 31  0.992323  700.000000 -530.962257     1240.485463
431  Line 13 - 14  0.237691  597.557529  283.732511     1320.306690
421  Line 04 - 14 -0.195680 -597.557529 -266.617079     1691.232877
420  Line 04 - 05  0.211101  597.557529 -147.670519     3530.196670
422  Line 05 - 06  0.204056  597.557529 -464.899174     5206.691806
434  Line 16 - 17  0.040256  597.557529  221.969830     9329.980588
452   Trf 13 - 12  0.023163  300.000000    7.075208    12646.237170

Bus 11
          Element      PTDF  Limit Used      actual  Transfer Limit
471  Line 06 - 11 -0.834986 -597.557529 -356.924904      288.187616
495   Trf 06 - 31  0.995318  700.000000 -530.962257     1236.752733
477  Line 13 - 14  0.160994  597.557529  283.732511     1949.296356
476  Line 10 - 13  0.147174  597.557529  291.165856     2081.832885
467  Line 04 - 14 -0.132726 -597.557529 -266.617079     2493.410857
466  Line 04 - 05  0.143279  597.557529 -147.670519     5201.237078
475  Line 10 - 11 -0.147174 -597.557529  358.834144     6498.373851
468  Line 05 - 06  0.138470  597.557529 -464.899174     7672.829516
480  Line 16 - 17  0.027178  597.557529  221.969830    13819.548846
484  Line 17 - 18  0.019646  597.557529  203.178353    20074.273430

Bus 12
          Element      PTDF  Limit Used      actual  Transfer Limit
517  Line 06 - 11 -0.758026 -597.557529 -356.924904      317.446400
543   Trf 11 - 12 -0.523327 -300.000000    0.489450      574.190612
544   Trf 13 - 12 -0.476794 -300.000000    7.075208      644.041679
521  Line 10 - 11  0.239093  597.557529  358.834144      998.454092
541   Trf 06 - 31  0.995155  700.000000 -530.962257     1236.955305
523  Line 13 - 14  0.238251  597.557529  283.732511     1317.203359
513  Line 04 - 14 -0.196288 -597.557529 -266.617079     1685.994301
512  Line 04 - 05  0.211812  597.557529 -147.670519     3518.346682
522  Line 10 - 13 -0.239093 -597.557529  291.165856     3717.061496
514  Line 05 - 06  0.204711  597.557529 -464.899174     5190.032304

Bus 13
          Element      PTDF  Limit Used      actual  Transfer Limit
563  Line 06 - 11 -0.680859 -597.557529 -356.924904      353.425048
567  Line 10 - 11  0.625358  597.557529  358.834144      381.738755
569  Line 13 - 14  0.315464  597.557529  283.732511      994.804534
587   Trf 06 - 31  0.994711  700.000000 -530.962257     1237.507433
559  Line 04 - 14 -0.259786 -597.557529 -266.617079     1273.896397
568  Line 10 - 13 -0.625358 -597.557529  291.165856     1421.143384
558  Line 04 - 05  0.280267  597.557529 -147.670519     2658.993201
560  Line 05 - 06  0.270881  597.557529 -464.899174     3922.226746
590   Trf 13 - 12  0.060612  300.000000    7.075208     4832.785448
589   Trf 11 - 12 -0.060600 -300.000000    0.489450     4958.571787

Bus 14
          Element      PTDF  Limit Used      actual  Transfer Limit
609  Line 06 - 11 -0.484539 -597.557529 -356.924904      496.621788
613  Line 10 - 11  0.445006  597.557529  358.834144      536.449810
605  Line 04 - 14 -0.426747 -597.557529 -266.617079      775.495667
633   Trf 06 - 31  1.000066  700.000000 -530.962257     1230.881018
604  Line 04 - 05  0.460391  597.557529 -147.670519     1618.685090
615  Line 13 - 14 -0.487119 -597.557529  283.732511     1809.188391
614  Line 10 - 13 -0.445006 -597.557529  291.165856     1997.104273
606  Line 05 - 06  0.444891  597.557529 -464.899174     2388.128110
618  Line 16 - 17  0.087609  597.557529  221.969830     4287.090351
622  Line 17 - 18  0.063141  597.557529  203.178353     6246.007757

Bus 15
          Element      PTDF  Limit Used      actual  Transfer Limit
655  Line 06 - 11 -0.411220 -597.557529 -356.924904      585.167610
659  Line 10 - 11  0.377636  597.557529  358.834144      632.152083
662  Line 14 - 15 -0.650779 -597.557529   15.799051      942.495962
664  Line 16 - 17  0.352241  597.557529  221.969830     1066.280469
679   Trf 06 - 31  0.999612  700.000000 -530.962257     1231.440055
651  Line 04 - 14 -0.238457 -597.557529 -266.617079     1387.841202
668  Line 17 - 18  0.268912  597.557529  203.178353     1466.573362
650  Line 04 - 05  0.491199  597.557529 -147.670519     1517.161166
648  Line 03 - 04  0.253178  597.557529   85.971831     2020.656208
649  Line 03 - 18 -0.267897 -597.557529  -44.841708     2063.165399

Bus 16
          Element      PTDF  Limit Used      actual  Transfer Limit
709  Line 15 - 16 -0.532840 -597.557529 -304.231715      550.495108
701  Line 06 - 11 -0.377036 -597.557529 -356.924904      638.221879
705  Line 10 - 11  0.346208  597.557529  358.834144      689.537458
710  Line 16 - 17  0.464645  597.557529  221.969830      808.332595
714  Line 17 - 18  0.356057  597.557529  203.178353     1107.629328
708  Line 14 - 15 -0.533075 -597.557529   15.799051     1150.600909
725   Trf 06 - 31  0.992972  700.000000 -530.962257     1239.674690
694  Line 03 - 04  0.346440  597.557529   85.971831     1476.693504
696  Line 04 - 05  0.501082  597.557529 -147.670519     1487.237712
695  Line 03 - 18 -0.354701 -597.557529  -44.841708     1558.258423

Bus 17
          Element      PTDF  Limit Used      actual  Transfer Limit
755  Line 15 - 16 -0.428904 -597.557529 -304.231715      683.896194
747  Line 06 - 11 -0.348573 -597.557529 -356.924904      690.336384
751  Line 10 - 11  0.320065  597.557529  358.834144      745.859073
760  Line 17 - 18  0.440143  597.557529  203.178353      896.025100
740  Line 03 - 04  0.435958  597.557529   85.971831     1173.474733
771   Trf 06 - 31  0.995832  700.000000 -530.962257     1236.114381
741  Line 03 - 18 -0.438498 -597.557529  -44.841708     1260.475124
754  Line 14 - 15 -0.429091 -597.557529   15.799051     1429.432403
742  Line 04 - 05  0.515241  597.557529 -147.670519     1446.367908
756  Line 16 - 17 -0.430730 -597.557529  221.969830     1902.647502

Bus 18
          Element      PTDF  Limit Used      actual  Transfer Limit
793  Line 06 - 11 -0.330702 -597.557529 -356.924904      727.641878
797  Line 10 - 11  0.303650  597.557529  358.834144      786.179431
801  Line 15 - 16 -0.355568 -597.557529 -304.231715      824.949976
787  Line 03 - 18 -0.575029 -597.557529  -44.841708      961.196428
786  Line 03 - 04  0.507579  597.557529   85.971831     1007.893742
817   Trf 06 - 31  1.000453  700.000000 -530.962257     1230.404883
788  Line 04 - 05  0.531454  597.557529 -147.670519     1402.243745
800  Line 14 - 15 -0.355719 -597.557529   15.799051     1724.272753
806  Line 17 - 18 -0.425611 -597.557529  203.178353     1881.379667
790  Line 05 - 06  0.550873  597.557529 -464.899174     1928.678122

Bus 19
          Element      PTDF  Limit Used      actual  Transfer Limit
849  Line 16 - 19 -0.984466 -597.557529 -501.921889       97.144686
847  Line 15 - 16 -0.523697 -597.557529 -304.231715      560.105964
839  Line 06 - 11 -0.370917 -597.557529 -356.924904      648.750595
843  Line 10 - 11  0.340554  597.557529  358.834144      700.985407
848  Line 16 - 17  0.457489  597.557529  221.969830      820.976457
852  Line 17 - 18  0.349686  597.557529  203.178353     1127.809451
846  Line 14 - 15 -0.523876 -597.557529   15.799051     1170.804884
863   Trf 06 - 31  0.976075  700.000000 -530.962257     1261.134909
832  Line 03 - 04  0.340427  597.557529   85.971831     1502.776506
834  Line 04 - 05  0.491961  597.557529 -147.670519     1514.811230

Bus 20
          Element      PTDF   Limit Used      actual  Transfer Limit
895  Line 16 - 19 -0.986346  -597.557529 -501.921889       96.959525
893  Line 15 - 16 -0.524707  -597.557529 -304.231715      559.027825
885  Line 06 - 11 -0.371628  -597.557529 -356.924904      647.509403
889  Line 10 - 11  0.341207   597.557529  358.834144      699.643865
894  Line 16 - 17  0.458361   597.557529  221.969830      819.414607
913   Trf 19 - 20 -1.001829 -1000.000000  122.741105     1120.691361
898  Line 17 - 18  0.350364   597.557529  203.178353     1125.626993
892  Line 14 - 15 -0.524888  -597.557529   15.799051     1168.547537
909   Trf 06 - 31  0.977957   700.000000 -530.962257     1258.707956
878  Line 03 - 04  0.341085   597.557529   85.971831     1499.877442

Bus 21
          Element      PTDF  Limit Used      actual  Transfer Limit
939  Line 15 - 16 -0.535746 -597.557529 -304.231715      547.509105
931  Line 06 - 11 -0.378939 -597.557529 -356.924904      635.016782
935  Line 10 - 11  0.347970  597.557529  358.834144      686.045878
940  Line 16 - 17  0.466823  597.557529  221.969830      804.561255
942  Line 16 - 21 -1.004569 -597.557529  274.707295      868.297572
944  Line 17 - 18  0.358113  597.557529  203.178353     1101.270202
938  Line 14 - 15 -0.536004 -597.557529   15.799051     1144.313437
955   Trf 06 - 31  0.998325  700.000000 -530.962257     1233.027578
924  Line 03 - 04  0.348359  597.557529   85.971831     1468.558864
926  Line 04 - 05  0.504042  597.557529 -147.670519     1478.503869

Bus 22
           Element      PTDF  Limit Used      actual  Transfer Limit
989   Line 16 - 24 -0.943655 -597.557529 -628.910624       33.225168
993   Line 22 - 23  1.000000  597.557529  650.000000       52.442471
994   Line 23 - 24  0.991853  597.557529  958.486204      363.893315
985   Line 15 - 16 -0.500389 -597.557529 -304.231715      586.195566
977   Line 06 - 11 -0.355133 -597.557529 -356.924904      677.584523
981   Line 10 - 11  0.325989  597.557529  358.834144      732.305029
986   Line 16 - 17  0.438814  597.557529  221.969830      855.915487
990   Line 17 - 18  0.333583  597.557529  203.178353     1182.252021
984   Line 14 - 15 -0.500455 -597.557529   15.799051     1225.597865
1001   Trf 06 - 31  0.932927  700.000000 -530.962257     1319.462569

Bus 23
           Element      PTDF  Limit Used      actual  Transfer Limit
1035  Line 16 - 24 -0.950991 -597.557529 -628.910624       32.968867
1040  Line 23 - 24  0.999183  597.557529  958.486204      361.223796
1031  Line 15 - 16 -0.504419 -597.557529 -304.231715      581.512221
1023  Line 06 - 11 -0.357930 -597.557529 -356.924904      672.289622
1027  Line 10 - 11  0.328563  597.557529  358.834144      726.568068
1032  Line 16 - 17  0.442200  597.557529  221.969830      849.361598
1036  Line 17 - 18  0.336317  597.557529  203.178353     1172.641216
1030  Line 14 - 15 -0.504496 -597.557529   15.799051     1215.780857
1047   Trf 06 - 31  0.940416  700.000000 -530.962257     1308.955033
1016  Line 03 - 04  0.327768  597.557529   85.971831     1560.816484

Bus 24
           Element      PTDF  Limit Used      actual  Transfer Limit
1081  Line 16 - 24 -0.996161 -597.557529 -628.910624       31.473924
1077  Line 15 - 16 -0.530370 -597.557529 -304.231715      553.058833
1069  Line 06 - 11 -0.375437 -597.557529 -356.924904      640.940090
1073  Line 10 - 11  0.344725  597.557529  358.834144      692.503834
1078  Line 16 - 17  0.462839  597.557529  221.969830      811.486713
1082  Line 17 - 18  0.354295  597.557529  203.178353     1113.137854
1076  Line 14 - 15 -0.530582 -597.557529   15.799051     1156.007138
1093   Trf 06 - 31  0.988429  700.000000 -530.962257     1245.372461
1062  Line 03 - 04  0.344805  597.557529   85.971831     1483.695705
1064  Line 04 - 05  0.498536  597.557529 -147.670519     1494.832966

Bus 25
           Element      PTDF  Limit Used      actual  Transfer Limit
1106  Line 02 - 03  0.526488  597.557529  364.999062      441.716556
1107  Line 02 - 25 -0.725837 -597.557529 -238.221859      495.063863
1115  Line 06 - 11 -0.283926 -597.557529 -356.924904      847.518806
1119  Line 10 - 11  0.260676  597.557529  358.834144      915.785819
1108  Line 03 - 04  0.506222  597.557529   85.971831     1010.595544
1123  Line 15 - 16 -0.262709 -597.557529 -304.231715     1116.542688
1139   Trf 06 - 31  0.968747  700.000000 -530.962257     1270.674651
1134  Line 26 - 27  0.248970  597.557529  263.795054     1340.573058
1110  Line 04 - 05  0.484231  597.557529 -147.670519     1538.992851
1112  Line 05 - 06  0.539283  597.557529 -464.899174     1970.128306

Bus 26
           Element      PTDF  Limit Used      actual  Transfer Limit
1180  Line 26 - 27  0.556292  597.557529  263.795054      599.977124
1161  Line 06 - 11 -0.315375 -597.557529 -356.924904      763.004755
1165  Line 10 - 11  0.289565  597.557529  358.834144      824.420714
1153  Line 02 - 25 -0.431173 -597.557529 -238.221859      833.390934
1169  Line 15 - 16 -0.344073 -597.557529 -304.231715      852.510407
1152  Line 02 - 03  0.265942  597.557529  364.999062      874.470623
1154  Line 03 - 04  0.471009  597.557529   85.971831     1086.148455
1175  Line 17 - 27 -0.552736 -597.557529   18.347924     1114.285034
1185   Trf 06 - 31  0.980868  700.000000 -530.962257     1254.972388
1156  Line 04 - 05  0.498794  597.557529 -147.670519     1494.059767

Bus 27
           Element      PTDF  Limit Used      actual  Transfer Limit
1207  Line 06 - 11 -0.331754 -597.557529 -356.924904      725.334508
1215  Line 15 - 16 -0.384020 -597.557529 -304.231715      763.829522
1211  Line 10 - 11  0.304616  597.557529  358.834144      783.686294

In [43]:
# All contingencies
all_dfs = []

for case_name,df in results.items():
    df_case = df.copy()
    all_dfs.append(df_case)

df_all = pd.concat(all_dfs, ignore_index=True)

df_all_sorted = df_all.sort_values(["Injection Bus","Transfer Limit"],ascending=[True,True])

top10_per_bus = df_all_sorted.groupby("Injection Bus",group_keys=False).head(10)

# Export the results into csvs

In [44]:
path = r"C:\Users\UI450907\Desktop\TE RWEST\Tesis\Phase3Results\Results"

with pd.ExcelWriter(path +r"\results_bus_by_bus_complete.xlsx", engine = "openpyxl") as writer:
    for bus,df_bus in df_all_sorted.groupby("Injection Bus"):
        sheet_name = f"Bus_{bus}"
        df_bus.to_excel(writer,sheet_name=sheet_name,index = False)

with pd.ExcelWriter(path +r"\results_bus_by_bus_top10.xlsx", engine = "openpyxl") as writer:
    for bus,df_bus in top10_per_bus.groupby("Injection Bus"):
        sheet_name = f"Bus_{bus}"
        df_bus.to_excel(writer,sheet_name=sheet_name,index = False)

In [45]:
grupo = df_all_sorted.groupby("Injection Bus")
grupo.get_group(1).head()

,Injection Bus,Element,PTDF,smax,loading,actual,margin,case,Limit Used,Transfer Limit
1796,1,Line 02 - 03,0.539423,597.557529,96.742803,585.512355,12.045173,Line_26_27_Cnt,597.557529,22.329736
64469,1,Line 02 - 03,0.806360,597.557529,76.838138,464.478099,133.079429,Line_01_39_Cnt,597.557529,165.037241
55543,1,Line 04 - 14,-0.140285,597.557529,95.304579,-566.892616,1164.450144,Line_06_11_Cnt,-597.557529,218.590105
32322,1,Line 26 - 27,0.390010,597.557529,81.988746,497.521086,100.036442,Line_02_03_Cnt,597.557529,256.497122
30500,1,Line 02 - 03,0.811006,597.557529,64.709424,380.955234,216.602295,Line_08_09_Cnt,597.557529,267.078535

# Compare PowerWorld vs Powerfactory

In [46]:
import re
import pandas as pd

def get_injection_bus(s):
    s = str(s)
    match = re.search(r'Bus\s+(\d+)', s)
    if match:
        return int(match.group(1))
    return None


def normalize_element(s):
    s = str(s).strip()
    s_low = s.lower()

    # detectar tipo
    if "transformer" in s_low or "trf" in s_low:
        elem_type = "Trf"
    elif "line" in s_low:
        elem_type = "Line"
    else:
        return None

    # caso PowerWorld: buscar "Bus xx ... Bus yy"
    bus_matches = re.findall(r'Bus\s+(\d+)', s, flags=re.IGNORECASE)

    if len(bus_matches) >= 2:
        b1, b2 = int(bus_matches[0]), int(bus_matches[1])
    else:
        # fallback para formato tipo "Line 02 - 03" o "Trf 12 - 13"
        nums = re.findall(r'\d+', s)
        if len(nums) < 2:
            return None
        b1, b2 = int(nums[0]), int(nums[1])

    b1, b2 = sorted([b1, b2])

    return f"{elem_type} {b1:02d}-{b2:02d}"


def normalize_ctg(s):
    s = str(s).strip()
    s_low = s.lower()

    # Base case
    if "base case" in s_low or s_low == "base_case":
        return "Base Case"

    # detectar tipo
    if s_low.startswith("t_") or "trf" in s_low or "transformer" in s_low:
        elem_type = "Trf"
    elif s_low.startswith("l_") or "line" in s_low:
        elem_type = "Line"
    else:
        return None

    # prioridad 1: buscar buses explícitos
    bus_matches = re.findall(r'Bus\s*(\d+)', s, flags=re.IGNORECASE)

    if len(bus_matches) >= 2:
        b1, b2 = int(bus_matches[0]), int(bus_matches[1])
    else:
        # fallback para formatos tipo Line_26_27_Cnt o Trf_11_12_Cnt
        nums = re.findall(r'\d+', s)
        nums = [int(x) for x in nums]

        if len(nums) < 2:
            return None

        # tomar los últimos dos "números de bus" más probables
        b1, b2 = nums[0], nums[1]

    b1, b2 = sorted([b1, b2])

    return f"{elem_type} {b1:02d}-{b2:02d}_Cnt"

In [47]:
powerworld_path = r"C:\Users\UI450907\Desktop\TE RWEST\Tesis\Phase3Results\PowerWorld\Book1.xlsx"

powerworld = pd.read_excel(powerworld_path, sheet_name= None)

for name,df in powerworld.items():
    df.columns = df.iloc[0]
    df = df.drop(0)
    df = df.reset_index(drop = True)
    df["Injection Bus"] = get_injection_bus(name)
    powerworld[name] = df

#Concatenate in one single dataframe
powerworld_df = pd.concat(powerworld.values(), ignore_index=True)
print(powerworld_df["Injection Bus"].unique())
print(powerworld_df.shape)
powerworld_df["Trans Lim"] = pd.to_numeric(powerworld_df["Trans Lim"], errors="coerce")
powerworld_df["element_key"] = powerworld_df["Limiting Element"].apply(normalize_element)
powerworld_df["ctg_key"] = powerworld_df["Limiting CTG"].apply(normalize_ctg)
powerworld_df.head()

[1 2 7]
(106, 9)

,Trans Lim,Limiting Element,Limiting CTG,% OTDF,% PTDF,Init Value,Pre-Trans Est,Limit Used,Injection Bus,element_key,ctg_key
0,3.66,Line Bus 02 (2) TO Bus 03 (3) CKT 1 [345.00 ...,L_000026Bus26-000027Bus27C1,53.31,43.68,364.26,595.61,597.56,1,Line 02-03,Line 26-27_Cnt
1,167.11,Line Bus 02 (2) TO Bus 03 (3) CKT 1 [345.00 ...,L_000001Bus01-000039Bus39C1,80.02,43.68,364.26,463.84,597.56,1,Line 02-03,Line 01-39_Cnt
2,168.86,Line Bus 04 (4) TO Bus 14 (14) CKT 1 [345.00...,L_000006Bus06-000011Bus11C1,-13.95,3.12,-270.41,-574.00,-597.56,1,Line 04-14,Line 06-11_Cnt
3,254.25,Line Bus 26 (26) TO Bus 27 (27) CKT 1 [345.0...,L_000002Bus02-000003Bus03C1,39.14,10.94,262.95,498.06,597.56,1,Line 26-27,Line 02-03_Cnt
4,271.39,Line Bus 02 (2) TO Bus 03 (3) CKT 1 [345.00 ...,L_000009Bus09-000039Bus39C1,80.02,43.68,364.26,380.39,597.56,1,Line 02-03,Line 09-39_Cnt

In [48]:
df_all_sorted["element_key"] = df_all_sorted["Element"].apply(normalize_element)
df_all_sorted["ctg_key"] = df_all_sorted["case"].apply(normalize_ctg)
df_all_sorted.head(5)

,Injection Bus,Element,PTDF,smax,loading,actual,margin,case,Limit Used,Transfer Limit,element_key,ctg_key
1796,1,Line 02 - 03,0.539423,597.557529,96.742803,585.512355,12.045173,Line_26_27_Cnt,597.557529,22.329736,Line 02-03,Line 26-27_Cnt
64469,1,Line 02 - 03,0.806360,597.557529,76.838138,464.478099,133.079429,Line_01_39_Cnt,597.557529,165.037241,Line 02-03,Line 01-39_Cnt
55543,1,Line 04 - 14,-0.140285,597.557529,95.304579,-566.892616,1164.450144,Line_06_11_Cnt,-597.557529,218.590105,Line 04-14,Line 06-11_Cnt
32322,1,Line 26 - 27,0.390010,597.557529,81.988746,497.521086,100.036442,Line_02_03_Cnt,597.557529,256.497122,Line 26-27,Line 02-03_Cnt
30500,1,Line 02 - 03,0.811006,597.557529,64.709424,380.955234,216.602295,Line_08_09_Cnt,597.557529,267.078535,Line 02-03,Line 08-09_Cnt

In [49]:
dup_pw = powerworld_df.duplicated(
    subset=["Injection Bus", "element_key", "ctg_key"],
    keep=False
)

powerworld_df[dup_pw].sort_values(
    ["Injection Bus", "element_key", "ctg_key"]
).head(20)
print(f"Duplicated in PowerWorld: {dup_pw.sum()}")

dup_pf = df_all_sorted.duplicated(
    subset=["Injection Bus", "element_key", "ctg_key"],
    keep=False
)


print(f"Duplicated in PF: {dup_pf.sum()}")

df_all_sorted[dup_pf].sort_values(
    ["Injection Bus", "element_key", "ctg_key"]
).head(20)
df_pf_clean = df_all_sorted.copy()
df_pf_clean = df_pf_clean.sort_values("Transfer Limit").drop_duplicates(
    subset=["Injection Bus", "element_key", "ctg_key"],
    keep="first"
)
dup_pf_clean = df_pf_clean.duplicated(
    subset=["Injection Bus", "element_key", "ctg_key"],
    keep=False
)

print("Duplicados después:", dup_pf_clean.sum())

Duplicated in PowerWorld: 0
Duplicated in PF: 0
Duplicados después: 0

In [50]:
# Create Rankings
powerworld_df = powerworld_df.sort_values(
    ["Injection Bus", "Trans Lim"],
    ascending=[True, True]
).copy()

powerworld_df["rank_pw"] = powerworld_df.groupby("Injection Bus").cumcount() + 1
df_pf_clean = df_pf_clean.sort_values(
    ["Injection Bus", "Transfer Limit"],
    ascending=[True, True]
).copy()

df_pf_clean["rank_pf"] = df_pf_clean.groupby("Injection Bus").cumcount() + 1

In [51]:
df_pf_clean.head()

,Injection Bus,Element,PTDF,smax,loading,actual,margin,case,Limit Used,Transfer Limit,element_key,ctg_key,rank_pf
1796,1,Line 02 - 03,0.539423,597.557529,96.742803,585.512355,12.045173,Line_26_27_Cnt,597.557529,22.329736,Line 02-03,Line 26-27_Cnt,1
64469,1,Line 02 - 03,0.806360,597.557529,76.838138,464.478099,133.079429,Line_01_39_Cnt,597.557529,165.037241,Line 02-03,Line 01-39_Cnt,2
55543,1,Line 04 - 14,-0.140285,597.557529,95.304579,-566.892616,1164.450144,Line_06_11_Cnt,-597.557529,218.590105,Line 04-14,Line 06-11_Cnt,3
32322,1,Line 26 - 27,0.390010,597.557529,81.988746,497.521086,100.036442,Line_02_03_Cnt,597.557529,256.497122,Line 26-27,Line 02-03_Cnt,4
30500,1,Line 02 - 03,0.811006,597.557529,64.709424,380.955234,216.602295,Line_08_09_Cnt,597.557529,267.078535,Line 02-03,Line 08-09_Cnt,5

In [52]:
# Hacer inner merge para solo  quedarme con casos comparables
df_compare = powerworld_df.merge(
    df_pf_clean,
    on=["Injection Bus", "element_key", "ctg_key"],
    how="inner",
    suffixes=("_pw", "_pf")
)
print(len(powerworld_df))
print(df_compare.shape)
df_compare.head()

106
(98, 22)

,Trans Lim,Limiting Element,Limiting CTG,% OTDF,% PTDF,Init Value,Pre-Trans Est,Limit Used_pw,Injection Bus,element_key,...,Element,PTDF,smax,loading,actual,margin,case,Limit Used_pf,Transfer Limit,rank_pf
0,3.66,Line Bus 02 (2) TO Bus 03 (3) CKT 1 [345.00 ...,L_000026Bus26-000027Bus27C1,53.31,43.68,364.26,595.61,597.56,1,Line 02-03,...,Line 02 - 03,0.539423,597.557529,96.742803,585.512355,12.045173,Line_26_27_Cnt,597.557529,22.329736,1
1,167.11,Line Bus 02 (2) TO Bus 03 (3) CKT 1 [345.00 ...,L_000001Bus01-000039Bus39C1,80.02,43.68,364.26,463.84,597.56,1,Line 02-03,...,Line 02 - 03,0.806360,597.557529,76.838138,464.478099,133.079429,Line_01_39_Cnt,597.557529,165.037241,2
2,168.86,Line Bus 04 (4) TO Bus 14 (14) CKT 1 [345.00...,L_000006Bus06-000011Bus11C1,-13.95,3.12,-270.41,-574.00,-597.56,1,Line 04-14,...,Line 04 - 14,-0.140285,597.557529,95.304579,-566.892616,1164.450144,Line_06_11_Cnt,-597.557529,218.590105,3
3,254.25,Line Bus 26 (26) TO Bus 27 (27) CKT 1 [345.0...,L_000002Bus02-000003Bus03C1,39.14,10.94,262.95,498.06,597.56,1,Line 26-27,...,Line 26 - 27,0.390010,597.557529,81.988746,497.521086,100.036442,Line_02_03_Cnt,597.557529,256.497122,4
4,271.39,Line Bus 02 (2) TO Bus 03 (3) CKT 1 [345.00 ...,L_000009Bus09-000039Bus39C1,80.02,43.68,364.26,380.39,597.56,1,Line 02-03,...,Line 02 - 03,0.811187,597.557529,64.323481,380.880410,216.677118,Line_09_39_Cnt,597.557529,267.111182,6

In [53]:
# Crear vista reducida
df_compare_view = df_compare[
    [
        "Injection Bus",
        "element_key",
        "ctg_key",
        "Trans Lim",
        "Transfer Limit",
        "rank_pw",
        "rank_pf",
    ]
].copy()

# Calcular error porcentual
df_compare_view["error_%"] = (
    (df_compare_view["Transfer Limit"] - df_compare_view["Trans Lim"]).abs()
    / df_compare_view["Trans Lim"].abs()
) * 100

# Diferencia de ranking
df_compare_view["rank_diff"] = (
    df_compare_view["rank_pf"] - df_compare_view["rank_pw"]
)

# Ordenar para visualizar
df_compare_view = df_compare_view.sort_values(
    ["Injection Bus", "rank_pw"],
    ascending=[True, True]
)

# Mostrar resultado
df_compare_view.head(20)

,Injection Bus,element_key,ctg_key,Trans Lim,Transfer Limit,rank_pw,rank_pf,error_%,rank_diff
0,1,Line 02-03,Line 26-27_Cnt,3.66,22.329736,1,1,510.102073,0
1,1,Line 02-03,Line 01-39_Cnt,167.11,165.037241,2,2,1.240356,0
2,1,Line 04-14,Line 06-11_Cnt,168.86,218.590105,3,3,29.450495,0
3,1,Line 26-27,Line 02-03_Cnt,254.25,256.497122,4,4,0.883824,0
4,1,Line 02-03,Line 09-39_Cnt,271.39,267.111182,5,6,1.576631,1
5,1,Line 06-11,Line 04-14_Cnt,298.87,309.921106,6,7,3.697630,1
6,1,Line 10-11,Line 04-14_Cnt,420.72,407.248639,7,10,3.201978,3
7,1,Line 03-04,Line 15-16_Cnt,459.64,468.136529,8,12,1.848518,4
8,1,Line 15-16,Line 03-04_Cnt,491.27,488.696854,9,15,0.523774,6
9,1,Line 06-11,Line 10-13_Cnt,524.70,540.008104,10,35,2.917497,25
10,1,Line 06-11,Line 01-39_Cnt,540.55,546.125911,11,38,1.031526,27
11,1,Line 01-39,Line 02-03_Cnt,565.31,564.281778,12,43,0.181886,31
12,1,Line 01-39,Line 01-02_Cnt,597.56,597.557529,13,45,0.000414,32
13,1,Line 01-02,Line 01-39_Cnt,597.56,597.557529,14,46,0.000414,32
14,1,Line 10-11,Line 09-39_Cnt,700.82,688.286422,15,52,1.788416,37
15,1,Line 10-11,Line 08-09_Cnt,700.99,688.059530,16,51,1.844601,35
16,1,Line 09-39,Line 01-02_Cnt,701.74,700.256968,17,54,0.211336,37
17,1,Line 08-09,Line 01-02_Cnt,701.75,697.168394,18,53,0.652883,35
18,1,Line 01-02,Line 09-39_Cnt,701.75,701.774577,19,55,0.003502,36
19,1,Line 01-02,Line 08-09_Cnt,701.93,701.811331,20,56,0.016906,36