In [8]:
import sys
print (sys.executable)

c:\Users\UI450907\Desktop\TE RWEST\Tesis\TesisRepo\thesis_env\Scripts\python.exe

In [9]:
import pandas as pd

In [10]:
filepath = r"C:\Users\UI450907\Desktop\TE RWEST\Tesis\Results _IEEE39\Weak_Bus_Selection\ShortCircuitCalculation.xlsx"
skss = pd.read_excel(filepath,
                     skiprows=12, header = 0)
skss.head()

,Unnamed: 0,Terminal,Grid,Connected Element \n (Branch),Nominal Voltage \n (kV),Fault Voltage \n (kV),Fault Voltage Angle \n (deg),c-Factor,"Sk"" \n (MVA)","Ik"" \n (kA)","Ik"" Angle \n (deg)",ip \n (kA),Ib \n (kA),Sb \n (MVA),Ik \n (kA),Ith \n (kA)
0,1,Bus 01,Grid,NaN,345.0,0.0,0.0,1.1,6083.765105,10.181053,-86.755808,26.628980,10.181053,6083.765105,10.181053,10.437836
1,2,NaN,NaN,Line 01 - 39,NaN,NaN,NaN,NaN,4072.634818,6.815469,92.329091,17.826150,6.815469,NaN,NaN,NaN
2,3,NaN,NaN,Line 01 - 02,NaN,NaN,NaN,NaN,2012.700980,3.368213,95.096112,8.809705,3.368213,NaN,NaN,NaN
3,4,Bus 02,Grid,NaN,345.0,0.0,0.0,1.1,9906.822329,16.578860,-84.517596,41.543370,16.261394,9717.118479,16.261394,16.843524
4,5,NaN,NaN,Trf 02 - 30,NaN,NaN,NaN,NaN,2974.563516,4.977870,91.503481,12.473565,4.882549,NaN,NaN,NaN

In [11]:
skss.columns

Index(['Unnamed: 0', 'Terminal', 'Grid', 'Connected Element \n (Branch)',
       'Nominal Voltage \n (kV)', 'Fault Voltage \n (kV)',
       'Fault Voltage Angle \n (deg)', 'c-Factor', 'Sk" \n (MVA)',
       'Ik" \n (kA)', 'Ik" Angle \n (deg)', 'ip \n (kA)', 'Ib \n (kA)',
       'Sb \n (MVA)', 'Ik \n (kA)', 'Ith \n (kA)'],
      dtype='object')

In [12]:
df_bus = skss[skss["Terminal"].str.contains("Bus", na = False)]
df_bus.head()
print(len(df_bus))

39

In [13]:
df_bus.columns

Index(['Unnamed: 0', 'Terminal', 'Grid', 'Connected Element \n (Branch)',
       'Nominal Voltage \n (kV)', 'Fault Voltage \n (kV)',
       'Fault Voltage Angle \n (deg)', 'c-Factor', 'Sk" \n (MVA)',
       'Ik" \n (kA)', 'Ik" Angle \n (deg)', 'ip \n (kA)', 'Ib \n (kA)',
       'Sb \n (MVA)', 'Ik \n (kA)', 'Ith \n (kA)'],
      dtype='object')

In [14]:
buses_sorted = df_bus.sort_values('Sk" \n (MVA)', ascending=True )
buses_sorted = buses_sorted.rename(columns = {'Sk" \n (MVA)':"Skss_MVA"})
buses_sorted.head(5)

,Unnamed: 0,Terminal,Grid,Connected Element \n (Branch),Nominal Voltage \n (kV),Fault Voltage \n (kV),Fault Voltage Angle \n (deg),c-Factor,Skss_MVA,"Ik"" \n (kA)","Ik"" Angle \n (deg)",ip \n (kA),Ib \n (kA),Sb \n (MVA),Ik \n (kA),Ith \n (kA)
43,44,Bus 12,Grid,NaN,138.0,0.0,0.0,1.1,3226.149887,13.497236,-87.517760,35.900714,13.497236,3226.149887,13.497236,13.933288
103,104,Bus 28,Grid,NaN,345.0,0.0,0.0,1.1,3844.491794,6.433676,-85.516751,16.349021,6.420190,3836.432687,6.420190,6.550674
106,107,Bus 29,Grid,NaN,345.0,0.0,0.0,1.1,5092.036528,8.521416,-86.162825,21.979226,8.163288,4878.034300,8.163288,8.702711
122,123,Bus 34,Grid,NaN,16.5,0.0,0.0,1.1,5555.462158,194.390762,-87.036744,511.082182,164.617725,4704.583357,164.617725,199.652351
100,101,Bus 27,Grid,NaN,345.0,0.0,0.0,1.1,5569.639584,9.320675,-85.544348,23.698315,9.320675,5569.639584,9.320675,9.491091

In [16]:
import matplotlib.pyplot as plt
import os
resultspath = r"C:\Users\UI450907\Desktop\TE RWEST\Tesis\Results _IEEE39\Weak_Bus_Selection"
outfile = os.path.join(resultspath,"Weakest_bus_Skss.png")

plt.figure(figsize = (10,4))
plt.grid(axis="y",linestyle = "--",alpha = 0.6)
plt.ylim(0, buses_sorted["Skss_MVA"].max() * 1.1)
plt.yticks(range(0, int(buses_sorted["Skss_MVA"].max() * 1.1) + 1, 5000))
plt.bar(buses_sorted["Terminal"], buses_sorted['Skss_MVA'])
plt.xticks(rotation=45)
plt.ylabel("Short-circuit power Sk'' (MVA)")
plt.xlabel("Bus")
plt.title("Weakest bus by short-circuit power")
plt.tight_layout()
plt.savefig(outfile,dpi = 300,bbox_inches = "tight")
plt.close()